#!/usr/bin/env bash

read -p "New version (enter nothing for patch): " VERSION;
VERSION=${VERSION:-patch};

git pull &&
git push &&
npm test &&
npm version $VERSION &&
npm publish &&
git push --follow-tags
